DEFAULT_FREQ = 44100
DEFAULT_TIME = 45
WAVE_ARRAY_LENGTH = DEFAULT_FREQ * DEFAULT_TIME

WINDOW_TIME = 5
WINDOW_SIZE = WINDOW_TIME * DEFAULT_FREQ

TRAIN_RATIO = 0.8

BATCH_SIZE = 16

FREQUENCY_LENGTH = 129
N_CHANNEL = 2
SPECTROGRAM_TIME_LENGTH = 15502
SPECTROGRAM_HALF_SECOND_LENGTH = 171
SPECTROGRAM_5_SECOND_LENGTH = 1721
MFCCS_TIME_LENGTH = 3876

LEARNING_RATE = 1e-4

SOUND_EXTENSION = ".wav"

# The minimum second to be labeled in the dynamics files.
MIN_TIME_END_POINT = 15